### ISSUE TITLE
[Feature Request] Dynamic size for window titles

### ISSUE THREAD

**Issue by kiarash96** [cedl38/xfce4-windowck-plugin#13]
It would be great to have a "dynamic" size option for window titles applet besides "at most" and "fixed" options.

**Comment by cedl38** [comment]
There is an "extend" option for that. Such option don't give expecting results in all case for some obscure reasons.. 
However you could use extended separators to simulate dynamic size.

**Comment by cedl38** [comment]
Duplicate of  #4
