### ISSUE TITLE
Compiling on Xubuntu 15.04

### ISSUE THREAD

**Issue by mehultikekar** [cedl38/xfce4-windowck-plugin#17]
I ran into issues compiling for Xubuntu 15.04. To get it to compile, I had to make two changes to the instructions in the readme -
1. There is no package called libxfce4-util-dev. I used libxfce4util-dev.
2. The autogen script gave an error about not finding libxfce4ui-1. So I installed libxfce4ui-1-dev

After these changes, it compiles and works perfectly.

**Comment by cedl38** [comment]
Thanks for you comment and sorry for the late answer. I'm very busy in this moment.
I've added the missing dependency to the debian packaging directory.
