### ISSUE TITLE
Missing packages error after running ./autogen.sh

### ISSUE THREAD

**Issue by afparsons** [cedl38/xfce4-windowck-plugin#18]
I'm encountering some sort of (likely resolvable) problem, though I'm not sure where to begin.
Xubuntu 14.04, XFCE 4.10

`$ ./autogen.sh --prefix=/usr`
> The required package gtk+-2.0 was not found on your system.

Ok, so after some googling, I believe I'm missing some sort of dependency. Therefore, 

`$ sudo apt-get install libx11-dev`
(~75mb...boahhh do I really need this?)

Then once more, 
`$ ./autogen.sh --prefix=/usr`
> The required package libxfce4ui-1 was not found on your system.

I'm confused. I'm not really familiar with compiling plugins. Gut feeling tells me that I'm missing something from `--prefix=/usr`

Going ahead and compiling with `make` just results in,
> No targets specified and no makefile found.  Stop.

Thanks for the help.

**Comment by cedl38** [comment]
Hello,
I've not very much time at tis moment that why I aswered you a bit late.
Your problem conserning missing dependency to build the plugin. After installed theme the plugin should compilling find. I've just tested it on Debian Jessie with success.
The package that you should install is `libxfce4ui-1-dev`, you have a complet list of requered packages for building the plugin on `debian/control` file.
You can also build a debian package with the folowing command:
`debuild -i -us -uc -b`
Install it with `sudo dpkg --install package_name.deb`

You can find documentation here about building a debian package here:
http://manpages.ubuntu.com/manpages/gutsy/en/man1/debuild.1.html
