### ISSUE TITLE
Themes on Xubuntu 15.04

### ISSUE THREAD

**Issue by alarien** [cedl38/xfce4-windowck-plugin#22]
Hi. Thank you for your awesome work, everything work exceptionally good, but there is this little problem with the number of themes available. I'll attach a screenshot.
![screenshot_2015-06-15_11-30-26](https://cloud.githubusercontent.com/assets/12892116/8156081/d0d7b5d2-1352-11e5-8508-b7e89a78d504.png)
And this is contents of the "themes" folder.
![screenshot_2015-06-15_11-33-30](https://cloud.githubusercontent.com/assets/12892116/8156083/dae26ed2-1352-11e5-8b51-7034761be850.png)
Expected behavior is being able to set as the theme "Numix" one, for example.
Creating "wckrc" file in /usr/share/themes/Numix/unity didn't help.
 Thank you in advance for the time invested.

**Comment by cedl38** [comment]
Thanks for the report. Now it's fixed!

**Comment by jncs12** [comment]
Hi!
Same problem here.

OS: Debian Buster 10
