### ISSUE TITLE
"(null)" string in windowck title bar

### ISSUE THREAD

**Issue by GloveAn** [cedl38/xfce4-windowck-plugin#23]
After windowck-title is configured to show active window's title, `(null)` string will be shown if there is no window opened on the desktop.

I did some hacking to `on_name_changed` funciton in `windowck-title.c` and the plugin works well now. 

1 change `const gchar *title_text;` to `const gchar *title_text = "";`
2 change `title_text = wnck_window_get_name(controlwindow);` to `if(wnck_window_has_name(controlwindow)) title_text = wnck_window_get_name(controlwindow);`
3 remove `title_text = "";`

**Comment by no5killz** [comment]
As already discribed from @GloveAn when all windows are closed on the workspace the plugin is falling into an "empty default" state (title = (null) and buttons with no function). It would be great if it could fall back to the Desktop so the added feature 'Log Out on close desktop' #12 works without changing the workspace.

**Comment by gcvl** [comment]
I can confirm the proposed "hack" works!
This is a very good plugin and I love it, but "(null)" is quite nasty...

**Comment by gcvl** [comment]
I can't seem to reproduce this issue anymore with any of the recent releases!

Maybe is it because I installed libxfce4panel-2.0-dev? Or some other updated library when I compiled and installed latest xfce4-vala-appmenu? 
I don't know but I'm quite happy for this.
