### ISSUE TITLE
Not correct windowck-title when unfocused window changes its title

### ISSUE THREAD

**Issue by nikitabobko** [cedl38/xfce4-windowck-plugin#56]
When unfocused window changes its title then it changes windowck-title even if there is another focused and maximized window. 

You can reproduce this issue by these steps:
1. Turn on some music in Spotify and maximize Spotify window
2. Alt+Tab to another window and maximize it
3. Wait when track changes in Spotify
4. Now windowck title is showing currently playing track in Spotify but you have another focused and maximized window at this moment. But it's expected that title of currently focused and maximized window to be shown in windowck-title not Spotify's window title

**Comment by chandlerkluser** [comment]
Did you have some trouble installing the plugin in Xubuntu? There is not a configure.ac file in the repository.
