### ISSUE TITLE
"Window Header - Buttons" unexpectedly left the panel

### ISSUE THREAD

**Issue by Mati20187** [cedl38/xfce4-windowck-plugin#62]
"Window Header - Buttons" unexpectedly left the panel, do you want to restart it? 
I get this message when I try to add either buttons or title to the panel on Xfce 4.14. 
I guess that windowck is not compatible with the newest version of Xfce.

**Comment by skpzk** [comment]
If that helps, I had the same problem after an update. It was solved by simply recompiling windowck, and now it works well with Xfce 4.14.

**Comment by Mati20187** [comment]
Fixed in the latest version
