### ISSUE TITLE
xfce 4.16 not work

### ISSUE THREAD

**Issue by JoveYu** [cedl38/xfce4-windowck-plugin#75]

**Comment by 20NE** [comment]
xfce 4.16 dumps gtk 2.0 code

**Comment by JoveYu** [comment]
i really need this plugin, please help update for 4.16

**Comment by SadmanTariq** [comment]
https://github.com/invidian/xfce4-windowck-plugin
This fork seems to be working

**Comment by JoveYu** [comment]
yes, it is work well

**Comment by 20NE** [comment]
> https://github.com/invidian/xfce4-windowck-plugin
> This fork seems to be working

Works, but window header icon missing.
